title: Silin Ruan's Homepage
page-top-title: Silin Ruan（阮思琳）
top-section-bg-text: 遥感科学与技术
home-subtitle: Silin Ruan&ensp;|&ensp;阮思琳
copyright-text: '&copy; Silin Ruan 2023-2024. All Rights Reserved.'
